import { Nunito } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/includes/navbar/Navbar";

export const metadata = {
  title: "Local Show",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className="flex flex-col min-h-screen"}>
        <Navbar />
        <div className="pt-[82px] flex-grow">{children}</div>
      </body>
    </html>
  );
}
